# docker compose -p -f docker-compose.yml up -d
services:
  global_mysql:
    image: mysql:8.0
    container_name: global_mysql
    expose:
      - "3306"
    env_file:
      - .env/mysql.env
    #environment:
    #  TZ: America/New_York
    #command: --default-time-zone=America/New_York
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - shared-global-network
  global_minio:
    image: minio/minio
    container_name: global_minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file:
      - .env/minio.env
    volumes:
      - miniodata:/data
    networks:
      - shared-global-network
    expose:
      - "9001"
      - "9000"

  globalapp_pma:
    image: phpmyadmin/phpmyadmin
    container_name: globalapp_pma
    expose:
      - "80"
    env_file:
      - .env/pma.env
    restart: unless-stopped
    networks:
      - shared-global-network

  globalapp_nginxPM:
    image: jc21/nginx-proxy-manager:latest
    container_name: globalapp_nginxPM
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_pm_data:/data
      - nginx_pm_letsencrypt:/etc/letsencrypt
    networks:
      - shared-global-network


volumes:
  mysql_data :
    external: true
    name: global_apps_mysql_data
  miniodata:
    external: true
    name: global_apps_miniodata
  nginx_pm_data:
    external: true
    name: global_apps_nginx_pm_data
  nginx_pm_letsencrypt:
    external: true
    name: global_apps_nginx_pm_letsencrypt

networks:
  shared-global-network:
    external: true
    
